name: Pawtograder
description:
  An action for automatically submitting and grading student coding submissions
author: Jonathan Bell <jon@jonbell.net>

branding:
  icon: heart
  color: red

inputs:
  grading_server:
    description: URL of the grading API server, e.g. https://api.pawtograder.com
    required: true
  handout_repo:
    description:
      '[DEPRECATED] This parameter is unused and will be removed in v4. Handout
      detection is now handled automatically by the API.'
    required: false
  regression_test_job:
    description: The ID of the Pawtograder regression test job to run
    required: false
  action_ref:
    description: The ref of the action, e.g. github.action_ref
    required: true
  action_repository:
    description: The repository of the action, e.g.  github.action_repository
    required: true

outputs:
  score:
    description: The score of the submission
  status:
    description: 'Human-readable status message'

runs:
  using: node20
  main: dist/index.js
